export const SET_CARDLIST = "SET_CARDLIST";
export const RESET_CARDLIST = "RESET_CARDLIST";
export const SET_CARDLIST_ERROR = "SET_CARDLIST_ERROR";
export const SET_DATA_BY_CURRENT_SORT = "SET_DATA_BY_CURRENT_SORT";
export const DELETE_CARDLIST_ITEM = "DELETE_CARDLIST_ITEM";
export const SET_START_ITEM = "SET_START_ITEM";