export const SET_CARDLIST = "SET_CARDLIST";
export const SET_CARDLIST_ERROR = "SET_CARDLIST_ERROR";
export const IS_CARDLIST_LOADING = "IS_CARDLIST_LOADING";
export const SET_CURRENT_SORT = "SET_CURRENT_SORT";
export const DELETE_CARDLIST_ITEM = "DELETE_CARDLIST_ITEM";
